language: node_js
node_js:
- '4.1'
- '4.0'
- '0.12'
script:
- npm run build
- npm test
after_success:
- test $TRAVIS_NODE_VERSION = "4.1" && npm run coverage && npm run sendcoverage
deploy:
  provider: npm
  email:
    secure: GA+/sXceRhY8j2nIb3eGY3uII+E1UYelCsvIlc5FC0QQcIYSG8BtkhKMRAkWhBypUtOxq5pYIjhCt5k2eOVGjAzF3SyZmhf+P846YyLdk18Crd42imJFp0db+wIjsj17zY4wSoCwFzUUs4WobOULAaW1gAHbc9NABVbnSIbpM5BsWZsAr+pBkb86NZnmCFk/GJTIeBhBNFUr0tlFx1DR8ueIQ4vadJQvQO5jEYXb3+dRcf+o0ST6Jjmcec38ce3l4IbLsFzdQPm3mX8mIev/E+vnH0osCgRCrGl4rm7kEfbPS4lTcAHyg0yq62Hb3rwDJbvXrEPqfDpKHSRgz8Au54iuUACj+tjZWmHntv4kz+hN6VK+p+8xs+V0Lcy9sZYHmz8SFmonICEITMIJLPP2nngO4c+yjAna3RnXUzoeP+K5PkPsHrameCGYFQSlNW00VY5m2dc6A/HNYqCnK+T+NdlXdwc8l/vpPpwfSuK7nOVTSacuaQZmn4xtfaOKCA3GQJUhr1uO+gppLYvd4zh1GUe36s9X+PoTBhxUxemA68d/KlN+MLD+yrHRCWFun7dbT2gJ1pF3ps1fALmiiEhbFOZ8QIre/lpOVruWfSVY+Ei6/daAwDW69pW8eEdBwyp/IMGFGeZ7NECZzW9gfgJrdlGyS2EoXjXNZi4t0BFT5Ug=
  api_key:
    secure: flhGr9o01h8WliCY5V6IyoluIL/sWDqu9z/Fgril+A0Wee2JUMwXLBscbTYI6+A37gY+EN7cpJ+5Wb6aoJWEcBkfvuMtS4EATSMr5ReG1h5PexLCPF84cEbwB0PFWgyfQ/cjjsw6SMngQN8A9NEeuacYeI7WUI3YyR9nOt2+x0Jw8zbPyZF3aywZbsB0NORTk5E6aL01DaOx+ylRkTR4E/YnEVQamm/xm4tgo3LHG8yYRKyi/Cqns3g58QwhKhMkjh6AR7WaWyRLPaaiBrmFseVyoPx+wzAzYkm2A5POH3YxFR7CRPcS46d++Q0Tx2DM53fQ1B9jR2/y0TzIEgC8KhazvZSdpe5B6YAsRXogNaG7UVPSDAfLCN6bM1pz7k4ROhQeebTxlPGk9eF+fPILxThH5n/h4brdDXztL5ixyREOw1SmTHZy54tF+Is6hRC4Tunt1h9Qa/XINM19ZXd10twHDe9vlroWsdlWjrki8XeEvYi6uYxOsbJzMEsWdUyTbqjlEQBcH2u36LufUuHQDCqJShccWbP1sM5JL3VFfhrI337fwOaCCA3OyjI9WSesLpGjZ1BEGuEzm1w7QuDv3ByMhFxPmyEzRDbkYUP63hhoieTVV7/xmF0rLlbQgV07Ef7HqRExj+9MLgTWbstldMsPHyxM/aNUrpU5esSncOQ=
  on:
    node: '4.1'
    tags: true
    repo: urbanmassage/contextual-promise
  skip_cleanup: true
